name: Test-Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm install
      - run: npm run build --if-present      

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults


      # Run the POSTMAN collection
      - name: Run POSTMAN collection on real time
        run: |
          newman run MinhaColecao.postman_collection.json -e MeuAmbiente.postman_environment.json 

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run MinhaColecao.postman_collection.json -e MeuAmbiente.postman_environment.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html


      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults
      
      
          
     
